//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzurreWebAppDB2
{
    using System;
    using System.Collections.Generic;

    public partial class orderDetial
    {
        public int Id { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public string productDesc { get; set; }
        public Nullable<int> quantity { get; set; }

        public virtual order order { get; set; }
    }
}
